config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#index'

  get 'grocery_lists/finished_shopping'

  resources :users, except: [:new, :create]
  resources :meals
  resources :groceries
  resources :measurements
  resources :ingredients do
    member do
      get :update_single_status, as: 'update_single_status'
      get :update_multiple_status, as: 'update_multiple_status'
    end
  end
  resources :cuisines
  resources :side_categories
  resources :entrees do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :sides do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :staples do
    member do
      get :update_staple_status, as: 'update_staple_status'
      get :update_staple_card_status, as: 'update_staple_card_status'
    end
  end
  resources :recipes
  resources :condiments
  resources :food_logs
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :recipeable, polymorphic: true

  has_rich_text :body

  belongs_to :user, inverse_of: :recipes

  before_save :set_name

  delegate :ingredients, to: :recipeable

  def set_name
    assign_attributes(name: recipeable.name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, except: %i[index new create]

  def index
    @recipes = policy_scope(Recipe)
    authorize @recipes
  end

  def show; end

  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    authorize @recipe

    if @recipe.save
      redirect_to recipes_path, notice: 'Successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe), notice: 'Update successful.'
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: 'Delete successful.'
  end

  private

    def set_recipe
      @recipe = Recipe.find(params[:id])
      authorize @recipe
    end

    def recipe_params
      params.require(:recipe).permit(policy(Recipe).permitted_attributes)
    end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this article from being saved:
      </p>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><center><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <br />
  <p>
    <%= f.label 'Is this an entree or a side?' %>
    <%= f.select :recipeable_type, [['Entree', 'Entree'], ['Side', 'Side']], prompt: true %>
  </p>
  <p id='js-entree'>
    <%= f.label 'Entree' %>
    <%= f.collection_select :recipeable_id, Entree.with_no_recipes, :id, :name, { prompt: true }, { allow_blank: true, class: 'js-entree-select' } %>
  </p>

  <p id='js-side'>
    <%= f.label 'Side' %>
    <%= f.collection_select :recipeable_id, Side.with_no_recipes, :id, :name, { prompt: true }, { allow_blank: true, class: 'js-side-select' }%>
  </p>

  <%= f.label 'Body' %>
  <%= f.rich_text_area :body %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <p>
    <%= f.submit %>
  </p>


<% end %>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Links</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%=recipe.name %></td>
        <td><%=recipe.user.fname %></td>
        <td>
          <%= link_to 'Show', recipe_path(recipe) %>
          <%= link_to 'Edit', edit_recipe_path(recipe) %>
          <%= link_to 'Destroy', recipe_path(recipe), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<div class='row'>
  <div class='col d-flex justify-content-center'>

    <p><%= link_to 'Create another recipe', new_recipe_path %></p>
  </div>
</div>

app/views/recipes/new.html.erb
<div class='row'>
  <div class='col'>
    The entree or side for this recipe must exist in the database before you create this recipe.
    If it doesn't exist yet, <%= link_to 'pop over real quick', new_entree_path %> to
    create it.
  </div>
</div>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class='row'>
  <div class='col d-flex justify-content-center'>
    <p><%= @recipe.name %></p>
  </div>
</div>
<div class='row'>
  <table>
    <% @recipe.ingredients.each do |ingredient| %>
      <tbody>
        <td><%= ingredient.pretty_quantity %></td>
        <td><%= ingredient.measurement %></td>
        <td><%= ingredient.name %></td>
      </tbody>
    <% end %>
  </table>
</div>
<div class='row'>
  <div class='col d-flex justify-content-center'>
    <div class='row'>
      <div class='col d-flex'>
        <%= @recipe.body %>
      </div>
    </div>
  </div>
</div>