config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#index'

  get 'grocery_lists/finished_shopping'

  resources :users, except: [:new, :create]
  resources :meals
  resources :groceries
  resources :measurements
  resources :ingredients do
    member do
      get :update_single_status, as: 'update_single_status'
      get :update_multiple_status, as: 'update_multiple_status'
    end
  end
  resources :cuisines
  resources :side_categories
  resources :entrees do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :sides do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :staples do
    member do
      get :update_staple_status, as: 'update_staple_status'
      get :update_staple_card_status, as: 'update_staple_card_status'
    end
  end
  resources :recipes
  resources :condiments
  resources :food_logs
end

app/models/condiment.rb
class Condiment < ApplicationRecord
  before_save :titleize_name
end

app/models/cuisine.rb
# frozen_string_literal: true

class Cuisine < ApplicationRecord
  before_save :titleize_name

  validates :name, uniqueness: true

  has_many :entrees, inverse_of: :cuisine, dependent: :destroy
end

app/models/entree.rb
# frozen_string_literal: true

class Entree < ApplicationRecord
  include Ingredientable
  include Recipeable

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  before_save :titleize_name

  has_one_attached :pic
  has_many :meals, inverse_of: :entree, dependent: :destroy
  has_many :food_logs, inverse_of: :entree, dependent: :destroy

  belongs_to :cuisine, inverse_of: :entrees
  belongs_to :user, inverse_of: :entrees

  validates :name, uniqueness: true
  validates :number_of_sides, presence: true

  scope :with_no_recipes, -> { includes(:recipe).where(recipes: { id: nil }).order(name: :asc) }

  enum status: {
    archived: 0,
    current: 1
  }

  def self.clear_present_sides
    current.each do |entree|
      entree.present_sides = []
      entree.save
    end
  end

  def sides
    return [] if present_sides.blank?
    return [] if number_of_sides.zero?

    Side.find(present_sides)
  end

  def assign_new_sides
    return if number_of_sides.zero?

    side_ids = []
    side_category_ids&.each do |id|
      category = SideCategory.find(id)
      next if category.sides.nil?

      side_ids << category.sides.pluck(:id).sample
    end
    update(present_sides: side_ids)
  end

  def assign_new_sides_from_one_category
    category = SideCategory.find(side_category_ids[0])
    return if category.sides.nil?

    side_ids = []
    potential_side_ids = category.sides.pluck(:id)
    number_of_sides.times do
      potential_side_id = potential_side_ids.sample
      side_ids << potential_side_id
      potential_side_ids.delete(potential_side_id)
    end
    update(present_sides: side_ids)
  end
end

app/models/food_log.rb
class FoodLog < ApplicationRecord
  belongs_to :user, inverse_of: :food_logs
  belongs_to :entree, inverse_of: :food_logs
end

app/models/grocery.rb
# frozen_string_literal: true

class Grocery < ApplicationRecord
  before_save :titleize_name

  has_many :ingredients, inverse_of: :grocery, dependent: :destroy
  has_many :staples, inverse_of: :grocery, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/grocery_list.rb
# frozen_string_literal: true

class GroceryList < ApplicationRecord
  before_save :collect_current_entrees
  before_save :populate_current_ingredients
  after_create :set_current_grocery_list

  enum status: {
    archived: 0,
    current: 1
  }

  def collect_current_entrees
    assign_attributes(entree_ids: Entree.current.pluck(:id))
  end

  def populate_current_ingredients
    assign_attributes(grocery_quantity: PopulateGroceryList.new.perform)
  end

  def set_current_grocery_list
    SetCurrentGroceryList.new.set_current_list
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  belongs_to :ingredientable, polymorphic: true
  belongs_to :grocery, inverse_of: :ingredients

  validates :grocery, presence: true

  delegate :name, to: :ingredientable, prefix: true
  delegate :calories_per_gram, to: :grocery

  scope :current_with_entree, lambda {
    joins(
      "JOIN entrees ON entrees.id = ingredients.ingredientable_id
       AND ingredients.ingredientable_type = 'Entree'"
    )
  }

  scope :current_with_side, lambda {
    joins(
      "JOIN sides ON sides.id = ingredients.ingredientable_id
       AND ingredients.ingredientable_type = 'Side'"
    )
  }

  enum status: {
    in_stock: 0,
    out_of_stock: 1
  }

  delegate :name, to: :grocery

  def flip_status
    if in_stock?
      update(status: :out_of_stock)
    elsif out_of_stock?
      update(status: :in_stock)
    end
  end

  def pretty_quantity
    quantity == quantity.to_i ? quantity.to_i : quantity
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :entree

  def name
    name = String.new
    sides = String.new
    name << "#{Entree.find(entree_id).name} with "
    side_ids.each do |id|
      sides << "#{Side.find(id).name} & "
    end
    name << sides[0..-4]
  end

  def sides
    Side.find(side_ids)
  end
end

app/models/measurement.rb
# frozen_string_literal: true

class Measurement < ApplicationRecord
  before_save :titleize_measure

  has_many :staples, inverse_of: :measurement, dependent: :destroy
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :recipeable, polymorphic: true

  has_rich_text :body

  belongs_to :user, inverse_of: :recipes

  before_save :set_name

  delegate :ingredients, to: :recipeable

  def set_name
    assign_attributes(name: recipeable.name)
  end
end

app/models/side.rb
# frozen_string_literal: true

class Side < ApplicationRecord
  include Ingredientable
  include Recipeable

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_one_attached :pic

  before_save :titleize_name

  belongs_to :user, inverse_of: :sides
  belongs_to :side_category, inverse_of: :sides

  delegate :name, to: :side_category, prefix: true

  scope :with_no_recipes, -> { includes(:recipe).where(recipes: { id: nil }).order(name: :asc) }

  enum status: {
    archived: 0,
    current: 1
  }
end

app/models/side_category.rb
# frozen_string_literal: true

class SideCategory < ApplicationRecord
  before_save :titleize_name

  has_many :sides, inverse_of: :side_category, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/staple.rb
# frozen_string_literal: true

class Staple < ApplicationRecord
  has_one_attached :pic

  belongs_to :user, inverse_of: :staples
  belongs_to :grocery, inverse_of: :staples
  belongs_to :measurement, inverse_of: :staples

  validates :name, presence: true

  enum status: {
    in_stock: 0,
    out_of_stock: 1
  }

  delegate :name, to: :grocery
  delegate :calories_per_gram, to: :grocery
  delegate :measure, to: :measurement

  def pretty_calories_per_gram
    calories_per_gram == calories_per_gram.to_i ? calories_per_gram.to_i : calories_per_gram
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entrees, inverse_of: :user, dependent: :destroy
  has_many :sides, inverse_of: :user, dependent: :destroy
  has_many :staples, inverse_of: :user, dependent: :destroy
  has_many :recipes, inverse_of: :user, dependent: :destroy
  has_many :food_logs, inverse_of: :user, dependent: :destroy

  enum role: {
    admin: 0,
    member: 1
  }
end

app/helpers/entrees_helper.rb
# frozen_string_literal: true

module EntreesHelper
end

app/helpers/meals_helper.rb
# frozen_string_literal: true

module MealsHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/helpers/sides_helper.rb
# frozen_string_literal: true

module SidesHelper
end

app/helpers/staples_helper.rb
# frozen_string_literal: true

module StaplesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/partials/_entree_cards.html.erb
<div class='container-fluid'>
  <div class='row'>
    <% @entrees.each do |entree| %>
      <div class='card mx-auto hvr-grow-shadow' id=<%= "js-entree-#{entree.id}" %>>
        <%= render 'entrees/entree_card_text', entree: entree %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_header.html.erb
<nav class='navbar navbar-expand-sm navbar-light bg-light'>
  <div>
    <%= link_to 'PUBGRUB', root_path, class: 'navbar-brand mb-0 h1' %>
  </div>

  <button type="button" class="btn-sm navbar-toggler navbar-toggler-right"
          data-toggle="collapse" data-target="#mainNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class='collaps navbar-collapse' id='mainNavbar'>
    <ul class='navbar-nav mr-auto'>
      <li class='nav-item dropdown'>
        <a class="nav-link dropdown-toggle
                <%= active_if(entrees_path) %>
                <%= active_if(new_entree_path) %>"
           href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Entrees
        </a>
        <div class='dropdown-menu'>
          <%= link_to 'See all Entrees', entrees_path, class: 'dropdown-item' %>
          <%= link_to 'Create an Entree', new_entree_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class='nav-item dropdown'>
        <a class="nav-link dropdown-toggle
                <%= active_if(sides_path) %>
                <%= active_if(new_side_path) %>"
           href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Sides
        </a>
        <div class='dropdown-menu'>
          <%= link_to 'See all Sides', sides_path, class: 'dropdown-item' %>
          <%= link_to 'Create a new Side', new_side_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class='nav-item dropdown'>
        <a class="nav-link dropdown-toggle
                <%= active_if(staples_path) %>
                <%= active_if(new_staple_path) %>"
           href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Staples
        </a>
        <div class='dropdown-menu'>
          <%= link_to 'See all Staples', staples_path, class: 'dropdown-item' %>
          <%= link_to 'Create a new Staple', new_staple_path, class: 'dropdown-item' %>
        </div>
      </li>

      <li class='nav-item dropdown'>
        <a class="nav-link dropdown-toggle
                <%= active_if(food_logs_path) %>
                <%= active_if(new_food_log_path) %>"
           href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Food Log
        </a>
        <div class='dropdown-menu'>
          <%= link_to 'See all Entries', food_logs_path, class: 'dropdown-item' %>
          <%= link_to 'Create a new Entry', new_food_log_path, class: 'dropdown-item' %>
        </div>
      </li>

      <% if current_user.admin? %>
        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                  <%= active_if(groceries_path) %>
                  <%= active_if(new_grocery_path) %>"
             href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
             Admin
           </a>
           <div class='dropdown-menu'>
             <%= link_to 'See all Groceries', groceries_path, class: 'dropdown-item' %>
             <%= link_to 'Create a Grocery', new_grocery_path, class: 'dropdown-item' %>
             <div class='dropdown-divider'></div>
             <%= link_to 'See all Measurements', measurements_path, class: 'dropdown-item' %>
             <%= link_to 'Create a Measurement', new_measurement_path, class: 'dropdown-item' %>
             <div class='dropdown-divider'></div>
             <%= link_to 'See all Ingredients', ingredients_path, class: 'dropdown-item' %>
             <%= link_to 'Create an Ingredient', new_ingredient_path, class: 'dropdown-item' %>
             <div class='dropdown-divider'></div>
             <%= link_to 'See Cuisines', cuisines_path, class: 'dropdown-item' %>
             <%= link_to 'Create a Cuisine', new_cuisine_path, class: 'dropdown-item' %>
             <div class='dropdown-divider'></div>
             <%= link_to 'See Recipes', recipes_path, class: 'dropdown-item' %>
             <%= link_to 'Create a Recipe', new_recipe_path, class: 'dropdown-item' %>
             <div class='dropdown-divider'></div>
             <%= link_to 'See Condiments', condiments_path, class: 'dropdown-item' %>
             <%= link_to 'Create a Condiment', new_condiment_path, class: 'dropdown-item' %>
           </div>
        </li>
      <% end %>

    </ul>
    <ul class='navbar-nav ml-auto'>
      <span class='nav-item mr-auto'>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link mr-sm-2' %>
      </span>
    </ul>
  </div>
</nav>

app/views/partials/_meal_cards.html.erb
<div class='container-fluid'>
  <div class='row'>
    <% @meals.each do |meal| %>
      <div class='card mx-auto hvr-grow-shadow'>
        <% if meal.pic.attached? %>
          <%= image_tag url_for(meal.pic), class: 'sized-image' %>
        <% end %>
        <div class='card-body d-flex flex-column'>
          <h5 class='card-title mt-auto'><%= meal.name %></h5>
          <p class='card-text mt-auto'>Calories per serving: XX</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_page_heading.html.erb
<div class='container-fluid page-heading'>
  <h1 class='text-center'><%= controller_name.titleize %></h1>
</div>

app/views/partials/_side_cards.html.erb
<div class='container-fluid'>
  <div class='row'>
    <% @sides.each do |side| %>
      <div class='card mx-auto hvr-grow-shadow' id=<%= "js-side-#{side.id}" %>>
        <%= render 'sides/side_card_text', side: side %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_staple_card_text.html.erb
<h5 class='card-header mt-auto'><%= staple.name %></h5>
<% if staple.pic.attached? %>
  <%= image_tag url_for(staple.pic), class: 'sized-image card-image-top' %>
<% end %>
<div class='card-body d-flex flex-column'>

  <div class='card-text mt-auto'><%= staple.quantity %> <%= staple.measure %></div>
  <div class='card-text mt-auto'>Calories per gram: <%= staple.pretty_calories_per_gram %></div>
  <div class='card-text mt-auto'>Calories per package: <%= staple.calories_per_package %></div>
  <div class='card-text mt-auto'><%= staple.status.humanize %></div>
</div>
<div class='card-body d-flex flex-column'>
  <%= link_to 'Change stock status', update_staple_card_status_staple_path(staple), remote: true %>
</div>
<% if staple.user_id == current_user.id %>
  <div class='card-body d-flex flex-column'>
    <div class='card-text mt-auto'>
      <%= link_to 'Update', edit_staple_path(staple), class: 'card-link' %>
    </div>
  </div>
<% end %>

app/views/partials/_staple_cards.html.erb
<div class='container-fluid'>
  <div class='row'>
    <% @staples.each do |staple| %>
      <div class='card mx-auto hvr-grow-shadow' id='js-staple-<%= staple.id %>'>
        <%= render 'partials/staple_card_text', staple: staple %>
      </div>
    <% end %>
  </div>
</div>