config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#index'

  get 'grocery_lists/finished_shopping'

  resources :users, except: [:new, :create]
  resources :meals
  resources :groceries
  resources :measurements
  resources :ingredients do
    member do
      get :update_single_status, as: 'update_single_status'
      get :update_multiple_status, as: 'update_multiple_status'
    end
  end
  resources :cuisines
  resources :side_categories
  resources :entrees do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :sides do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :staples do
    member do
      get :update_staple_status, as: 'update_staple_status'
      get :update_staple_card_status, as: 'update_staple_card_status'
    end
  end
  resources :recipes
  resources :condiments
  resources :food_logs
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  belongs_to :ingredientable, polymorphic: true
  belongs_to :grocery, inverse_of: :ingredients

  validates :grocery, presence: true

  delegate :name, to: :ingredientable, prefix: true
  delegate :calories_per_gram, to: :grocery

  scope :current_with_entree, lambda {
    joins(
      "JOIN entrees ON entrees.id = ingredients.ingredientable_id
       AND ingredients.ingredientable_type = 'Entree'"
    )
  }

  scope :current_with_side, lambda {
    joins(
      "JOIN sides ON sides.id = ingredients.ingredientable_id
       AND ingredients.ingredientable_type = 'Side'"
    )
  }

  enum status: {
    in_stock: 0,
    out_of_stock: 1
  }

  delegate :name, to: :grocery

  def flip_status
    if in_stock?
      update(status: :out_of_stock)
    elsif out_of_stock?
      update(status: :in_stock)
    end
  end

  def pretty_quantity
    quantity == quantity.to_i ? quantity.to_i : quantity
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, except: %i[index new create]
  before_action :set_grocery_list, only: %i[index update_single_status update_multiple_status]

  def index
    @ingredients = Ingredient.all
    authorize @ingredients
  end

  def show; end

  def new
    @ingredient = Ingredient.new
    authorize @ingredient
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    authorize @ingredient

    if @ingredient.save
      redirect_to ingredients_path, notice: 'Created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @ingredient.update(ingredient_params)
    redirect_to ingredient_path(@ingredient)
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  def update_single_status
    @ingredient.flip_status
    respond_to do |format|
      format.html { redirect_to ingredients_path }
      format.js { render layout: false }
    end
  end

  def update_multiple_status
    @ingredient.flip_status
    respond_to do |format|
      format.html { redirect_to ingredients_path }
      format.js { render layout: false }
    end
  end

  private

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
      authorize @ingredient
    end

    def set_grocery_list
      @grocery_list = GroceryList.current.last
    end

    def ingredient_params
      params.require(:ingredient).permit(policy(Ingredient).permitted_attributes)
    end
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class='container-fluid'>
  <div class='d-flex justify-content-center'>
    <%= form_for @ingredient do |f| %>
      <% if @ingredient.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@ingredient.errors.count, "error") %> prohibited
            this article from being saved:
          </p>
          <% @ingredient.errors.full_messages.each do |msg| %>
            <li><center><%= msg %></li>
          <% end %>
        </div>
      <% end %>

      <p>
        <%= f.label 'Grocery' %>
        <%= f.collection_select :grocery_id, Grocery.all, :name, :id, prompt: true %>
      </p>

      <p>
        <%= f.label 'Measurement' %>
        <%= f.collection_select :measurement, Measurement.all, :measure, :measure, prompt: true %>
      </p>

      <p>
        <%= f.label 'Quantity' %>
        <%= f.number_field :quantity, step: 0.01 %>
      </p>

      <p>
        <%= f.submit %>
      </p>

    <% end %>
  </div>
</div>

app/views/ingredients/_grocery_list.html.erb
<div class='row d-flex justify-content-center'>
  <ul>
    <% @grocery_list.grocery_quantity.each do |k, v| %>
      <%= render 'ingredient_k_v', k: k, v: v %>
    <% end %>
  </ul>
</div>

app/views/ingredients/_ingredient_k_v.html.erb
<% ingredient = Ingredient.find(v["ingredient_id"]) %>

<% if v.key?("Whole") && v.key?("ingredient_id") %>
  <div id=<%= "js-ingredient-#{v['ingredient_id']}" %>>
    <%= render 'simple_k_v', ingredient: ingredient, k: k, v: v %>
  </div>
<% else %>
  <div id=<%= "js-ingredient-#{v['ingredient_id']}" %>>
    <%= render 'multiple_k_v', ingredient: ingredient, k: k, v: v %>
  </div>
<% end %>

app/views/ingredients/_multiple_k_v.html.erb
<li class=<%= "#{ingredient.status}" %>><%= link_to "#{k}", update_multiple_status_ingredient_path(ingredient), remote: true %></li>
<ul>
  <% v.each do |key, val| %>
    <% next if key == "ingredient_id" %>
    <li class=<%= "#{ingredient.status}" %>><%= key %>: <%= val %></li>
  <% end %>
</ul>

app/views/ingredients/_simple_k_v.html.erb
<li class=<%= "#{ingredient.status}" %>>
  <%= link_to "#{k}", update_single_status_ingredient_path(ingredient), remote: true %>: <%= v.values[0] %>
</li>

app/views/ingredients/_staple_k_v.html.erb
<% staple = Staple.find(v["staple_id"]) %>

<div id=<%= "js-staple-#{v["staple_id"]}" %>>
  <li class=<%= "#{staple.status}" %>>
    <%= link_to "#{staple.name}", update_staple_status_staple_path(staple), remote: true %>
  </li>

  <ul>
    <% v.each do |key, val| %>
      <% next if key == 'staple_id' %>
      <li class=<%= "#{staple.status}" %>><%= key %>: <%= val %></li>
    <% end %>
  </ul>
</div>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col d-flex justify-content-center'>
      <h3>This week's shopping list.</h3>
    </div>
  </div>
  <br />
  <div class='row d-flex justify-content-center'>
    <ul>
      <% @grocery_list.grocery_quantity.each do |k, v| %>
        <% if v["ingredient_id"].present? %>
          <%= render 'ingredient_k_v', k: k, v: v %>
        <% else %>
          <%= render 'staple_k_v', v: v %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class='row'>
  <div class='col d-flex justify-content-center'>
    <%= link_to 'Finished Shopping', grocery_lists_finished_shopping_path,
                                     class: 'btn btn-secondary mb-5',
                                     data: { confirm: 'You sure?' } %>
  </div>
</div>

app/views/ingredients/show.html.erb
<%= @ingredient.name %>
<%= @ingredient.measurement %>
<%= @ingredient.quantity %>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/ingredients/update_multiple_status.js.erb
var ingredient_id = "<%= j(params[:id]) %>";
"<%= j(key = @ingredient.name) %>"
"<%= j(val = @grocery_list.grocery_quantity[@ingredient.name]) %>"
$("#js-ingredient-" + ingredient_id).html(
    "<%= j(render partial: 'ingredients/multiple_k_v', locals: {ingredient: @ingredient, k: key, v: val}) %>"
);

app/views/ingredients/update_single_status.js.erb
var ingredient_id = "<%= j(params[:id]) %>";
"<%= j(key = @ingredient.name) %>"
"<%= j(val = @grocery_list.grocery_quantity[@ingredient.name]) %>"
$("#js-ingredient-" + ingredient_id).html(
    "<%= j(render partial: 'ingredients/simple_k_v', locals: {ingredient: @ingredient, k: key, v: val}) %>"
);

app/views/ingredients/update_status.js.erb
var ingredient_id = "<%= j(params[:id]) %>";
"<%= j(key = @ingredient.grocery) %>"
"<%= j(val = @grocery_list.grocery_quantity[@ingredient.grocery]) %>"
console.log("<%= j(val = @grocery_list.grocery_quantity[@ingredient.grocery]) %>")
$("#js-ingredient-" + ingredient_id).html(
    "<%= j(render partial: 'ingredients/simple_k_v', locals: {ingredient: @ingredient, k: key, v: val}) %>"
);