config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#index'

  get 'grocery_lists/finished_shopping'

  resources :users, except: [:new, :create]
  resources :meals
  resources :groceries
  resources :measurements
  resources :ingredients do
    member do
      get :update_single_status, as: 'update_single_status'
      get :update_multiple_status, as: 'update_multiple_status'
    end
  end
  resources :cuisines
  resources :side_categories
  resources :entrees do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :sides do
    member do
      get :finalize_calories, as: 'finalize_calories'
    end
  end
  resources :staples do
    member do
      get :update_staple_status, as: 'update_staple_status'
      get :update_staple_card_status, as: 'update_staple_card_status'
    end
  end
  resources :recipes
  resources :condiments
  resources :food_logs
end

app/models/side.rb
# frozen_string_literal: true

class Side < ApplicationRecord
  include Ingredientable
  include Recipeable

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_one_attached :pic

  before_save :titleize_name

  belongs_to :user, inverse_of: :sides
  belongs_to :side_category, inverse_of: :sides

  delegate :name, to: :side_category, prefix: true

  scope :with_no_recipes, -> { includes(:recipe).where(recipes: { id: nil }).order(name: :asc) }

  enum status: {
    archived: 0,
    current: 1
  }
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  before_action :set_side, except: %i[index new create]

  def index
    @sides = policy_scope(Side).order(created_at: :desc)
    authorize @sides
  end

  def show; end

  def new
    @side = Side.new
    authorize @side
  end

  def create
    @side = Side.new(side_params)
    authorize @side

    if @side.save
      redirect_to sides_path, notice: 'Successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @side.update(side_params)
    redirect_to side_path(@side), notice: 'Update successful.'
  end

  def destroy
    @side.destroy
    redirect_to side_path(@side), notice: 'Destroy successful.'
  end

  def finalize_calories
    @sides = policy_scope(Side).order(created_at: :desc)
    CalculateCalories.new.perform(@side)

    respond_to do |format|
      format.html { redirect_to side_path(@side) }
      format.js { render layout: false }
    end
  end

  private

    def set_side
      @side = Side.find(params[:id])
      authorize @side
    end

    def side_params
      params.require(:side).permit(policy(Side).permitted_attributes)
    end
end

app/helpers/sides_helper.rb
# frozen_string_literal: true

module SidesHelper
end

app/views/sides/_form.html.erb
<div class='container-fluid'>
  <div class='d-flex justify-content-center'>
    <%= form_for @side do |f| %>
      <% if @side.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@side.errors.count, "error") %> prohibited
            this article from being saved:
          </p>
          <% @side.errors.full_messages.each do |msg| %>
            <li><center><%= msg %></li>
          <% end %>
        </div>
      <% end %>
      <p>
        <%= f.label 'Name' %>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label 'Pic' %>
        <%= f.file_field :pic %>
      </p>

      <p>
        <%= f.label 'Side Category' %>
        <%= f.collection_select :side_category_id, SideCategory.all, :id, :name, prompt: true %>
      </p>


      <p>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :status, value: :archived %>
      </p>

      <p>
        Don't see a grocery for this meal? <%= link_to 'Add it real quick', new_grocery_path %> before continuing.
      </p>


      <fieldset>
        <p>
          <%= f.fields_for :ingredients do |ingredients_form| %>
            <%= render 'ingredient_fields', f: ingredients_form, entree: @side %>
          <% end %>
          <%= link_to_add_fields 'Add Ingredients', f, :ingredients %>
        </p>
      </fieldset>

      <p>
        <%= f.submit %>
      </p>
    <% end %>
  </div>
</div>

app/views/sides/_ingredient_fields.html.erb
<div class='nested-fields'>
  <%= f.hidden_field :_destroy %>
  <%= f.hidden_field :ingredientable_id, value: @side.id %>
  <%= f.hidden_field :ingredientable_type, value: 'Side' %>

  <hr />
  <p>
    <%= f.label 'Grocery' %>
    <%= f.collection_select :grocery, Grocery.all.order(name: :asc), :name, :name, prompt: true %>
  </p>

  <p>
    <%= f.label 'Measurement' %>
    <%= f.collection_select :measurement, Measurement.all, :measure, :measure, prompt: true %>
  </p>

  <p>
    <%= f.label 'Quantity' %>
    <%= f.number_field :quantity, step: 0.01 %>
  </p>

  <p>
    <%= link_to 'Remove', '#', class: "remove_fields" %>
  </p>
  <hr />
</div>

app/views/sides/_side_card_text.html.erb
<% if side.pic.attached? %>
  <%= image_tag url_for(side.pic), class: 'sized-image' %>
<% else %>
  <%= link_to 'Add a pic', edit_side_path(side), class: 'card-text mx-auto' %>
<% end %>
<div class='card-body d-flex flex-column'>
  <h5 class='card-title mt-auto'><%= side.name %></h5>
  <p class='card-text mx-auto'><%= side.side_category_name %></p>
  <p class='card-text mt-auto'>Calories per serving: <%= side.calories_per_gram %></p>
  <p class='card-text mt-auto'><%= link_to 'Update Calories', finalize_calories_side_path(side), remote: true %></p>
  <p><%= link_to 'Delete this', side_path(side), method: :delete %></p>
  <p>
    <% if side.user_id == current_user.id %>
      <%= link_to 'Update this side', edit_side_path(side) %>
    <% end %>
  </p>
</div>

app/views/sides/create.html.erb
<h1>Sides#create</h1>
<p>Find me in app/views/sides/create.html.erb</p>

app/views/sides/destroy.html.erb
<h1>Sides#destroy</h1>
<p>Find me in app/views/sides/destroy.html.erb</p>

app/views/sides/finalize_calories.js.erb
var side_id = "<%= j(params[:id]) %>"
console.log(side_id);
$("#js-side-" + side_id).html("<%= j(render partial: 'sides/side_card_text', locals: { side: @side }) %>");

app/views/sides/index.html.erb
<%= render 'partials/side_cards' %>

app/views/sides/show.html.erb
<div>
  <p><%= link_to 'Back to dashboard', root_path %> </p>
  <p><%= link_to 'Back to all sides', sides_path %></p>
  <p><%= link_to 'Calculate Calories', finalize_calories_side_path(@side) %></p>
</div>
<div>
  <h3><%= @side.name %></h3>
  <p><%= @side.side_category_name %></p>
  <p>
    <% if @side.pic.attached? %>
      <%= image_tag url_for(@side.pic), class: 'sized-image' %>
    <% else %>
      Add a picture!
    <% end %>
  </p>
  <p>
    Ingredients:
  </p>
  <hr />
  <% @side.ingredients.each do |ingredient| %>
    <p>
      <%= ingredient.name %><br />
      <%= ingredient.measurement unless ingredient.measurement.nil? %><br />
      <%= ingredient.quantity unless ingredient.quantity.nil? %><br />
    </p>

  <% end %>
  <hr />
</div>

app/views/sides/update.html.erb
<h1>Sides#update</h1>
<p>Find me in app/views/sides/update.html.erb</p>